const STAGES_PER_WORLD = 3;
const WORLD_COUNT = 3;
const LEVEL_COUNT = STAGES_PER_WORLD * WORLD_COUNT;

const LEVEL_HP = [
  300, 300, 300,
  450, 450, 450,
  600, 600, 600
];

module.exports = {
  STAGES_PER_WORLD: STAGES_PER_WORLD,
  WORLD_COUNT: WORLD_COUNT,
  LEVEL_COUNT: LEVEL_COUNT,
  LEVEL_HP: LEVEL_HP
};
